name: Build for MacOS
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: WillAbides/setup-go-faster@v1.6.0
      id: setup-go-faster
      with:
        go-version: "*"

    - name: Update AppVersion and BuildDate
      run: chmod +x ./updateAppVersionAndBuildDate.sh && ./updateAppVersionAndBuildDate.sh
    
    - name: go get fyne
      run: go get fyne.io/fyne/v2/cmd/fyne

    - name: go install fyne
      run: go install fyne.io/fyne/v2/cmd/fyne
      
    - name: Package (macOS)
      run: fyne package -release && mkdir pkg && mv anarchy-droid.app pkg/Anarchy-Droid.app
    
    # - name: Build
    #   run: go build -o build/ . && mv build/anarchy-droid build/Anarchy-Droid_darwin_amd64

    - name: Extract binary
      run: mkdir -p build && cp pkg/Anarchy-Droid.app/Contents/MacOS/anarchy-droid build/Anarchy-Droid_darwin_amd64

    - uses: actions/upload-artifact@v2
      with:
        name: Anarchy-Droid (MacOS)
        path: pkg
    
    - uses: actions/upload-artifact@v2
      with:
        name: Anarchy-Droid_darwin_amd64
        path: build/Anarchy-Droid_darwin_amd64